kind: ExternalService
name: result
spec:
  image: fandoghpaas/result:${VERSION}
  env:
    - name: PGPASSWORD
      value: db123
      hidden: true
    - name: ENVIRONMENT
      value: STAGING

  resources:
    memory: 100Mi
